--CREATE DATABASE 情感分析系统;
USE 情感分析系统;
CREATE TABLE 用户信息表(
	ID INT,
	用户名  VARCHAR(20) NOT NULL,
	密码 VARCHAR(20) NOT NULL,
	年龄 INT NOT NULL,
	身份 CHAR(6) CHECK(身份 IN ('顾客', '管理员')),
	PRIMARY KEY (ID),
);

CREATE TABLE 评论数据表(
	评论ID INT PRIMARY KEY,
	顾客ID INT FOREIGN KEY REFERENCES 用户信息表(ID),
	商品ID INT  NOT NULL,
	评论时间 DATETIME NOT NULL,
	评论内容 VARCHAR(500) NOT NULL,
);
CREATE TABLE 结论数据表(
	结论ID INT PRIMARY KEY,
	评论ID INT FOREIGN KEY REFERENCES 评论数据表(评论ID),
	属性极性对 VARCHAR(300) NOT NULL,
);
