# Generated by Django 4.0.4 on 2022-04-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('评论id', models.IntegerField(db_column='评论ID', primary_key=True, serialize=False)),
                ('商品id', models.IntegerField(db_column='商品ID')),
                ('评论时间', models.DateTimeField()),
                ('评论内容', models.CharField(db_collation='Chinese_PRC_CI_AS', max_length=500)),
            ],
            options={
                'db_table': '评论数据表',
                'managed': False,
            },
        ),
    ]
