# Generated by Django 4.0.4 on 2022-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('用户名', models.CharField(db_collation='Chinese_PRC_CI_AS', max_length=20)),
                ('密码', models.CharField(db_collation='Chinese_PRC_CI_AS', max_length=20)),
                ('年龄', models.IntegerField()),
                ('身份', models.CharField(blank=True, db_collation='Chinese_PRC_CI_AS', max_length=6, null=True)),
            ],
            options={
                'db_table': '用户信息表',
                'managed': False,
            },
        ),
    ]
