# Generated by Django 4.0.4 on 2022-04-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
